### ISSUE TITLE
3G -> 2G 전환 불가능

### ISSUE THREAD

**Issue by ghost** [FullGreen/cyanogenmod_kernel_samsung_smdk4412#2]
커널부분인것 같아 여기에 올립니다.
http://fullgreen.rf.gd/Bug_Report/781
여기에서 3G -> 2G 전환이 안된다는 버그 제보가 있습니다.

**Comment by FullGreen** [comment]
#2 픽스 완료

https://github.com/FullGreen/cyanogenmod_device_samsung_c1skt/commit/50be8d64b190a51de55a3fb9c638664c881e4db2
