### ISSUE TITLE
진짜로 전화가 안됩니다.

### ISSUE THREAD

**Issue by ghost** [FullGreen/cyanogenmod_kernel_samsung_smdk4412#4]
전화를 걸었더니 신호음이 안갑니다.
그래서 화면을 봤더니 거는중.. 그러던 중 상대방이 받았습니다.
제가 여보세요 했는데 아무소리도 안나요.
그래서 스피커폰으로 바꾸니 이제 소리가 들리더군요.

추가
CM13 BETA 버전 기준.
- [ ] Wi-Fi EAP-SIM/AKA 해결
- [x] 커널 조정이 불가능 (Kernel Aduitor 기준) / Android 자체에서 차단.
- [ ] 통화시 확률로 통화음이 안들림. (기지국과의 통신 문제추정. 비행기 모드 켰다 끄니 해결됨)

**Comment by FullGreen** [comment]
beta1 말씀하시는건가요?

**Comment by ghost** [comment]
@FullGreen 넵

**Comment by ghost** [comment]
![screenshot_20160902-084457](https://cloud.githubusercontent.com/assets/5405019/18188214/36a9ac52-70eb-11e6-8f88-8f07fe19973f.png)
Google Play 서비스 무한강종으로 logcat 뽑았는데 이게 계속 도배되네요.
커널튜너 앱으로 가버너변경, 클럭변경 등을 했는데 적용안되는 일이 있었긴한데..

**Comment by FullGreen** [comment]
혹시 3G 요금제 사용중이신가요?

**Comment by ghost** [comment]
아뇨 LTE 요금제예요.
통신사는 SKT

**Comment by ghost** [comment]
![screenshot_20160903-093529](https://cloud.githubusercontent.com/assets/5405019/18221556/05660404-71ba-11e6-9431-6514ba4ae31c.png)
@FullGreen 추가 - T wifi secure 안됨.

**Comment by FullGreen** [comment]
혹시 eap-sim으로 인증 되시나요?

**Comment by ghost** [comment]
@FullGreen EAP-SIM, EAP-AKA, EAP-`AKA
3개 다 안됩니다. 모두 인증문제 뜨네요.

**Comment by ghost** [comment]
@FullGreen 방금 발견한 버그인데, 폰 종료할때 진동 울린 후 바로 꺼지지 않고 종료시간의 2배(시간재보니 정확히 2배)만큼 기다리다가 꺼지잖아요.
여기에 문제가 있는지 충전하면서 전원을 꺼버리면 폰이 안꺼지네요.
커널 자체문제일 수 있으니 보류하죠.

수정.
CPU 가버너 바꾸면 전원안꺼짐.

**Comment by FullGreen** [comment]
그런 버그도 있었군요... 감사합니다 :+1:

**Comment by ghost** [comment]
@FullGreen BETA2 에서 해결.
